### ISSUE TITLE
FETAURE/BUG FIX - Allow specifying timezone

### ISSUE THREAD

**Issue by mak001** [dynamic/silverstripe-elemental-countdown#23]
Would allow for all clients to show the same end time, instead of the time relative to the client's timezone.
We should be able to add a timezone dropdown and then append it to the config.End variable. We might need to wrap it in a `Dat.parse()` when passing it to the countdown method in javascript.

https://github.com/dynamic/silverstripe-elemental-countdown/blob/17ed367fdd861b62a84b8850641b86f8103aaac1/src/Elements/ElementCountDown.php#L93-L103

could be changed to 
```php
     public function setClientConfig() 
     { 
         $clientArray = [ 
             'End' => $this->End . ' ' . $this->Timezone, 
             'Elapse' => $this->Elapse, 
         ]; 
  
         $this->client_config = ArrayData::create($this->encodeArrayValues($clientArray)); 
  
         return $this; 
     } 
```

https://github.com/OnesandZerosTechnology/silverstripe-timezones

**Comment by muskie9** [comment]
I'd categorize this as a bug as it creates inconsistent information to end users.
